version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install nodejs
      - npm i -g expo-cli
  pre_build:
    commands:
      - expo login -u sinewave -p papitopiernaslargas69 --non-interactive
      - npm i
  build:
    commands:
      - expo build:android --non-interactive --release-channel beta