version: 0.2

env:
  variables:
    EXPO_DEBUG: "true"
phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y nodejs
      - npm i -g expo-cli
  pre_build:
    commands:
      - expo login -u sinewave -p papitopiernaslargas69 --non-interactive
      - npm i
      - export NODE_OPTIONS=--max_old_space_size=4096
  build:
    commands:
      - expo build:android --non-interactive --release-channel beta